# Cli Colors
export CLICOLOR=1
# use yellow for dir?~@~Ys
export LSCOLORS=dxfxcxdxbxegedabagacad

# history
export HISTSIZE=5000

export SVN_EDITOR=vim

alias ll="ls -la"
#alias m='mutt -f {my.imap.hostname}inbox'
alias gs="git status"
alias gsi="git status --ignored"
alias gd="git diff"
alias gl="git log"
alias glp="git log -p"
alias gb="git branch"
alias greb="git pull --rebase"

alias dxprod="source ~/prodbuilds/dx-toolkit/environment && echo Using dx at \'$(which dx)\'"
alias tml="tmux list-sessions"
alias rprog="rsync -avz --progress"

#PATH=$PATH:/usr/local/mysql/bin:/usr/local/sbin
#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

