# cli colors
export CLICOLOR=1

# use yellow for dir?~@~Ys
export LSCOLORS=dxfxcxdxbxegedabagacad

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

# history
export HISTSIZE=5000

export SVN_EDITOR=vim

alias ll="ls -la"
#alias m='mutt -f {my.imap.hostname}inbox'
alias gs="git status"
alias gsi="git status --ignored"
alias gd="git diff"
alias gl="git log"
alias glp="git log -p"
alias gb="git branch"
alias greb="git pull --rebase"

alias dxprod="source ~/prodbuilds/dx-toolkit/environment"
alias tml="tmux list-sessions"
alias rprog="rsync -avz --progress"

# Adding homebrew node and python paths:
export PATH="/usr/local/opt/node@6/bin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
